"""initial schema

Revision ID: 865ee3ccf432
Revises: 
Create Date: 2026-03-12 23:31:26.107583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '865ee3ccf432'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('wpn_id', sa.String(length=100), nullable=True),
    sa.Column('wpn_level', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('discovery_source', sa.String(length=20), nullable=False),
    sa.Column('first_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_validated', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stores_address_state_city', 'stores', [sa.literal_column("(address->>'state'), (address->>'city')")], unique=False)
    op.create_index('ix_stores_name', 'stores', ['name'], unique=False)
    op.create_index('ix_stores_status', 'stores', ['status'], unique=False)
    op.create_table('online_presences',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('channel_type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('sells_mtg_singles', sa.Boolean(), nullable=True),
    sa.Column('estimated_inventory_size', sa.String(length=20), nullable=True),
    sa.Column('pricing_method', sa.String(length=20), nullable=True),
    sa.Column('last_price_update_detected', sa.DateTime(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_online_presences_status', 'online_presences', ['status'], unique=False)
    op.create_index('ix_online_presences_store_id', 'online_presences', ['store_id'], unique=False)
    op.create_table('validation_logs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('presence_id', sa.Uuid(), nullable=True),
    sa.Column('check_type', sa.String(length=30), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['presence_id'], ['online_presences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_validation_logs_store_id', 'validation_logs', ['store_id'], unique=False)
    op.create_index('ix_validation_logs_timestamp', 'validation_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_validation_logs_timestamp', table_name='validation_logs')
    op.drop_index('ix_validation_logs_store_id', table_name='validation_logs')
    op.drop_table('validation_logs')
    op.drop_index('ix_online_presences_store_id', table_name='online_presences')
    op.drop_index('ix_online_presences_status', table_name='online_presences')
    op.drop_table('online_presences')
    op.drop_index('ix_stores_status', table_name='stores')
    op.drop_index('ix_stores_name', table_name='stores')
    op.drop_index('ix_stores_address_state_city', table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
